# Generated by Django 5.2.5 on 2025-08-08 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
        ('cases', '0005_delete_analysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='cases.case'),
        ),
        migrations.RemoveField(
            model_name='document',
            name='case',
        ),
        migrations.AlterField(
            model_name='analysis',
            name='document_original',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses_as_original', to='cases.document'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='document_contested',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses_as_contested', to='cases.document'),
        ),
        migrations.DeleteModel(
            name='Case',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
