# Generated by Django 5.2.5 on 2025-08-12 13:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_forgerytype_analysis_automatic_result_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comparison',
            name='forgery_type',
        ),
        migrations.AddField(
            model_name='comparison',
            name='automatic_result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comparison',
            name='forgery_types',
            field=models.ManyToManyField(blank=True, related_name='analyses', to='analysis.forgerytype'),
        ),
        migrations.AddField(
            model_name='forgerytype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forgerytype',
            name='example_image',
            field=models.ImageField(blank=True, null=True, upload_to='forgery_examples/'),
        ),
        migrations.AddField(
            model_name='forgerytype',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forgerytype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='forgerytype',
            name='description',
            field=models.TextField(blank=True, default='Sem descrição'),
            preserve_default=False,
        ),
    ]
