# Generated by Django 5.2.5 on 2025-08-12 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_remove_comparison_forgery_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparison',
            name='document_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_comparisons', to='analysis.documentversion'),
        ),
        migrations.AddField(
            model_name='comparison',
            name='pattern_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pattern_comparisons', to='analysis.documentversion'),
        ),
    ]
