# Generated by Django 5.2.5 on 2025-08-12 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author',
        ),
    ]
