# Generated by Django 5.2.5 on 2025-08-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='annotations',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
