# Generated by Django 5.2.5 on 2025-08-07 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_document_annotations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='cases.case')),
                ('document_contested', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses_as_contested', to='cases.document')),
                ('document_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses_as_original', to='cases.document')),
            ],
        ),
    ]
