# Generated by Django 5.2.5 on 2025-08-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='final_report',
            field=models.FileField(blank=True, null=True, upload_to='laudos/'),
        ),
    ]
