# Generated by Django 5.2.5 on 2025-08-08 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_case_final_report'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Analysis',
        ),
    ]
