# Generated by Django 5.2.5 on 2025-08-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_delete_analysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('in_progress', 'Em Andamento'), ('under_review', 'Em Revisão'), ('awaiting_validation', 'Aguardando Validação'), ('completed', 'Concluído'), ('rejected', 'Rejeitado')], default='pending', max_length=20),
        ),
    ]
